### ISSUE TITLE
Seems like Require-from does not work with "webpackHotMiddleware"

### ISSUE THREAD

**Issue by KindWizzard** [agoldis/webpack-require-from#10]
Hi there! Nice plugin, thank's a lot! 

But it seems like webpack-hot-middlware ignores require-from plugin code. That's what I see in the generated file:

```javascript
 	function hotDownloadManifest(requestTimeout) { // eslint-disable-line no-unused-vars
 		requestTimeout = requestTimeout || 10000;
 		return new Promise(function(resolve, reject) {
 			if(typeof XMLHttpRequest === "undefined")
 				return reject(new Error("No browser support"));
 			try {
 				var request = new XMLHttpRequest();
 				var requestPath = __webpack_require__.p + "" + hotCurrentHash + ".hot-update.json";
 				request.open("GET", requestPath, true);
 				request.timeout = requestTimeout;
 				request.send(null);
 			} catch(err) {
 				return reject(err);
 			}
```

So, there is not redefinition of src property, only the original "__webpack_require__.p".

**Comment by KindWizzard** [comment]
PS: I know that it's strange issue and dev build can be done without such features as dynamic output path definition, so if there is no quick solution it's ok :)

**Comment by agoldis** [comment]
@KindWizzard thanks for the feedback! Only options `path` and `methodName` will work with HMR requests. The mentioned options defined a getter for `__webpack_require__.p` and every attempt to access the variable will invoke the module.

Can you please describe your use case? 

I shared a repo where you can experiment with https://github.com/agoldis/webpack-require-from-10

**Comment by agoldis** [comment]
@KindWizzard ?

**Comment by KindWizzard** [comment]
@agoldis Sorry for the long answer. I've replace "replaceSrcMethodName" with "methodName" (with some changes in my code, not a big deal) and everything works just fine! Thanks again 👍
