### ISSUE TITLE
Gracefully fallback to `__webpack_public_path__`

### ISSUE THREAD

**Issue by agoldis** [agoldis/webpack-require-from#12]
webpack allows users to explicitly https://webpack.js.org/guides/public-path/#on-the-fly. The plugin should respect the value of `__webpack_public_path__`, but still override it when a configuration option is set.

**Comment by agoldis** [comment]
@davidmjiang that's great! thank you for that! Do you need any guidance / context?

**Comment by davidmjiang** [comment]
I think I understand it. If a configuration option is set (path, variableName or methodName), then we set the value as we are doing it now. In this case, users can not change the public path using __webpack_public_path = something. If none of those are set, then we should allow users to change public path using __webpack_public_path__. Does that sound right?

**Comment by agoldis** [comment]
@davidmjiang indeed :)
