### ISSUE TITLE
Extra request made to original url in IE/Edge

### ISSUE THREAD

**Issue by davidmjiang** [agoldis/webpack-require-from#14]
In IE/Edge, download starts when script.src is set. In __webpack_require__.e, the src is first set to the original url, then later overwritten by webpackRequireFrom using replaceSrcMethodName. This causes an unnecessary GET request sent to the original URL before we request the URL that we actually want.  Can we move the replaceSrc code to where the src is set the first time?
![image](https://user-images.githubusercontent.com/16966368/53901736-7e986f00-3ff4-11e9-97df-2fcb85b6f676.png)

**Comment by agoldis** [comment]
Good catch! 
I will take a look and try to resolve during the weekend

**Comment by agoldis** [comment]
Hey, @davidmjiang please check out `webpack-require-from@1.7.0-beta.0`.
If you're interested, more details here https://github.com/agoldis/webpack-require-from/pull/15
