### ISSUE TITLE
Modifying URL in web worker chunk

### ISSUE THREAD

**Issue by sushain97** [agoldis/webpack-require-from#16]
I'm running to issues with an inline web worker with a dynamic import not being intercepted by this library. Since inline web workers are blobs and therefore need an absolute URL to successfully import scripts, I'm attempting to use this library to fix-up the URL.

e.g. 

```
const md = await import(/* webpackChunkName: "markdown-it" */ 'markdown-it');
```

inside a web worker becomes something like

```
const md = await __webpack_require__.e(/* import() | markdown-it */ 2).then(__webpack_require__.t.bind(null, 264, 7));
```

which calls into

```
r.e = function(e) {
        var n = [];
        return n.push(Promise.resolve().then(function() {
            t[e] || importScripts(e + ".ee0bc93119ec2d63cc28.worker.js")
        })),
        Promise.all(n)
    }
```

Unfortunately, this isn't prepending the `path` it should be per the config below since it never actually results in the code below being called.

```
Object.defineProperty(r, "p", {
        get: function() {
            return "http://localhost:8080/"
        }
    }),
```

```
new WebpackRequireFrom({
      path: 'http://localhost:8080/',
      suppressErrors: true,
    }),
```

(For now, I've used a hardcoded `path` to see if I could get it minimally working. In practice, it would be a variable that is set similar to the advice in https://stackoverflow.com/a/22582695/1266600.)

Am I misunderstanding how something works or perhaps the intent of this library?

**Comment by agoldis** [comment]
Hi @sushain97! Thanks for discovering and reporting that issue!
Could you please share the webpack version you're using and may be a minimal reproducable example of the code. 
Also, did you try to use other options,  e.g. https://github.com/agoldis/webpack-require-from#replacesrcmethodname?

**Comment by sushain97** [comment]
Awesome! Thank you for investigating (and taking up the enhancement).

**Comment by agoldis** [comment]
@sushain97 Can you please share your webpack config

**Comment by sushain97** [comment]
@agoldis https://github.com/sushain97/web2fs-notepad/blob/issue-25/webpack.config.js

**Comment by agoldis** [comment]
@sushain97 That was an interesting problem!

Would appreciate if you try to use 
```
yarn add https://github.com/agoldis/webpack-require-from.git#next
```
and follow the instructions https://github.com/agoldis/webpack-require-from/tree/next#web-worker

There's also a working example https://github.com/agoldis/webpack-require-from/tree/next/example

I am waiting for your feedback regarding:
1. The documentation and instructions
2. Whether the solution is working for you

**Comment by sushain97** [comment]
The solution works for me and the documentation looks good as well! The only note I have is that since `window` isn't supported in a web worker, `self` is required instead: https://github.com/sushain97/web2fs-notepad/commit/06b3ece074f1c1c96d9bb75436181147943f6026#diff-028b78cada5fa9a59260b989f3b86ffeR52. The URL needs to be passed from the main thread to the web worker as a message (might be useful to note this as well).

Thanks for your fast (and great) work!

**Comment by agoldis** [comment]
Great, I will roll out a new npm release later this week

**Comment by agoldis** [comment]
Resolved by https://github.com/agoldis/webpack-require-from/releases/tag/v1.8.0
