### ISSUE TITLE
Thank you :)

### ISSUE THREAD

**Issue by pavelloz** [agoldis/webpack-require-from#27]
Hello,

Ive been using webpack-require-from for at least 2 years, never had any issues, everything works as expected, so i just wanted to say thank you.

It is a live saver for so long for me and other people after they learn it exist, its truly a gem.

---

Nevermind the title - i double checked my work and this made me appreciate the quality of this piece of software even more :)

**Comment by agoldis** [comment]
You made my day, man! 😃

**Comment by pavelloz** [comment]
:-)
