### ISSUE TITLE
[webpack 5] Uncaught ReferenceError: __webpack_require__ is not defined

### ISSUE THREAD

**Issue by dmarcautan** [agoldis/webpack-require-from#44]
I get `Uncaught ReferenceError: __webpack_require__ is not defined` in runtime for a bundle emitted by Webpack 5.  The specifics of this bundle is that it doesn't import in any way other modules and it seems Webpack 5 won't inject its bootstrap code in such bundles thus the runtime exception when plugin tries to extend __webpack_require__

**Comment by agoldis** [comment]
🤔 interesting, wondering if it'd be appropriate just removing the plugin for such bundles :)

**Comment by LinFeng1997** [comment]
I meet the same problem in 1.8.4 version @agoldis
